# Generated by Django 3.2.21 on 2024-03-08 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_alter_produto_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'variação', 'verbose_name_plural': 'variações'},
        ),
    ]
