# Generated by Django 5.0.3 on 2024-03-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produto", "0006_alter_produto_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="preco_marketing",
            field=models.FloatField(verbose_name="preço"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="preco_marketing_promocional",
            field=models.FloatField(default=0, verbose_name="preço promocional"),
        ),
    ]
